### ISSUE TITLE
Problem with model training-ELBO before training: nan

### ISSUE THREAD

**Issue by jinb88187** [bioFAM/MOFA2#60] opened 2021-01-07 15:47 UTC
Hello

I am following evodevo tutorial for MEFISTO to use for my data and I'm stuck in the model training part. I haven't changed the default iteration, so I expect it to be 1000 and I have kept the default parameters and other settings as was in that tutorial. The problem is that model training goes only up to iteration 19 with the same message of : Iteration 1: time=13.85, ELBO=nan, deltaELBO=nan (nan%), Factors=5. It also has not also defined the ELBO (ELBO before training: nan) and I don't know why. Then, after iteration 19 it shows the error message :

 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'get_ls' 

I had upgraded mofapy2, but this was the command I used for model training:  
MOFAobject <- run_mofa(MOFAobject_untrained, use_basilisk = TRUE, outfile = "my_file.hdf5")

I also see this warning: Warning: 0 features(s) in view ... are full of missing values, please consider removing them before training the model...  [I get this error for all the views]

Your help would be greatly appreciated.

**Comment by gtca** [comment] 2021-01-07 20:55
Hello, thanks for reaching out. Not sure why it happens but maybe more details would help to figure it out.
Does it run fine on the data from the tutorial? What happens if you don't use MEFISTO options? Or a single view?

We can also try to investigate the problem if you could somehow forward us a subset of your data to reproduce the error (e.g. as an .rds file).

**Comment by jinb88187** [comment] 2021-01-08 00:08
Hello, thank you for the quick reply. I can build the trained model for that tutorial. I tried MOFA alone (without setting the covariate) and used single view, but none resolved this issue. I've uploaded a subset of this dataset I'm using with a single view; if you could give some advice for this problem, that would be perfect. Thanks
Link to file: https://easyupload.io/i8a1na

**Comment by gtca** [comment] 2021-01-11 02:14
Hey @jinb88187, from the file it seems like there are a lot of missing values.
This code shows that each feature is defined exactly once in the data, which doesn't seem right:
```R
> load("mofa_data_subset.RData")  # loads `All`
> All %>% group_by(feature) %>% count %>% pull(n) %>% map_lgl(~ . == 1) %>% all
[1] TRUE
# or simpler
> length(unique(All$feature)) == nrow(All)
[1] TRUE
```

Also, is it intended that the sample names are the same across groups? Together with the fact that the groups have the same amount of samples and the view is labelled `"batch_t"` it makes me wonder if the groups/views are correctly defined. _Views_ are supposed to represent modalities while _groups_ are merely sample groups.

There are functions `plot_data_overview()` and `plot_ascii_data()` that might help to check that the data is structured as you expect:
```
> model <- create_mofa(All)
> plot_ascii_data(model)

                  estr.          prog.
                   14             14
                ________       ________
               |        |     |        |
batch_t  1372  |   4%   |     |   4%   |
               |________|     |________|
```

**Comment by jinb88187** [comment] 2021-01-14 08:47
Hi, thanks a lot for the input. I will check their names. I mistakenly thought that the mean expression values of my triplicates are needed, that's why every feature is there only once. So, for entering the sample names, do I need to write sample 1, replicate A, B or C or just sample 1 for all triplicates?

**Comment by gtca** [comment] 2021-01-14 14:28
I'm not sure the design is clear to me but I'll try to give a few comments that will hopefully help.


> that's why every feature is there only once

In a long format, I would still expect to have a feature (e.g. gene CD8A) to have multiple values (for different samples), at most it's N (number of samples) rows per feature.

> mean expression values of my triplicates are needed

It might be a good start as a simpler case (1 matrix vs 3 matrices). Not sure that explains the previous point though. Maybe thinking of it as of matrices `samples x features` would help?

> just sample 1 for all triplicates

Is there a simple hierarchy of samples, i.e. 3 batches (replicates)? Then those would be groups. If there are the same samples that has been profiled 3 times, one can try to either treat such measurements as views, to just put them all together as one group and study inter-replicate variation after the training, or to start with average values per sample indeed (that might be enough depending on the data).

**Comment by gtca** [comment] 2021-04-20 13:39
I will close this issue but please feel free to reach out in case there are more questions.

**Closed by gtca** 2021-04-20 13:39 UTC
