### ISSUE TITLE
create_mofa() ignores colData columns

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA2#40] opened 2020-05-04 16:00 UTC
When the input to `create_mofa()` is a MultiAssayExperiment object, the colData information of is not propagated to the `.@samples_metadata` slot, and hence this information is lost.

**Comment by gtca** [comment] 2020-05-06 20:25
Hello @frederikziebell, that's an expected behaviour in the current version of MOFA+.
The recommended workflow, which is described in the vignettes, is to add the metadata needed to the trained model in your R session.

I can see an appeal to store metadata to make MOFA+ experience smoother, and there's [a branch saving_metadata](../tree/saving_metadata). In addition to existing formats (Seurat objects in R and AnnData in Python), I've added MultiAssayExperiment colData support as well:

```r
model <- create_mofa(mae_object, save_metadata = TRUE)
```

It works, though there might be unexpected problems with saving metadata e.g. due to HDF5 encoding. 
Please feel free to try it out and let us know if there are any problems.

**Comment by frederikziebell** [comment] 2020-05-08 12:13
Thank you for implementing this. I used the stored metadata in MOFA v1 (via the colData of the MultiAssayExperiment in model@InputData) very extensively. The major advantage is that you don't have to remember from which object the model was generated to produce the right metadata.

**Comment by gtca** [comment] 2020-06-03 20:07
Just to continue with that request, we have merged `saving_metadata` branch, which also has a feature requested here, to `master`. Please let us know if there are any issues that you encounter since this is a new feature. And thanks again for your feedback!

**Closed by gtca** 2020-06-03 20:07 UTC
