### ISSUE TITLE
python dependecies

### ISSUE THREAD

**Issue by llrs** [bioFAM/MOFA2#41] opened 2020-05-12 09:55 UTC
I've been trying to install and use MOFA for some time. I tried both R 3.6.3 and Bioconductor 3.10 and the latest R 4.0.0 and Bioconductor 3.11.
On both set ups I can install the R package but I have problems installing the python dependency. 

```r
library(reticulate)
py_install("mofapy", envname = "r-reticulate", method="auto")
```
This commands end with:
```
Successfully built mofapy sklearn
Installing collected packages: scikit-learn, sklearn, mofapy
Successfully installed mofapy-1.2 scikit-learn-0.20.4 sklearn-0.0
```

This detected python2.7 installed but there are other python versions installed (including 3.4)

But when following the [CLL vignette](http://bioconductor.org/packages/release/bioc/vignettes/MOFA/inst/doc/MOFA_example_CLL.html)  I run `MOFAobject <- runMOFA(MOFAobject)` I get :
```
Error in value[[3L]](cond) : 
  mofapy package not found. Make sure that Reticulate is pointing to the right Python binary.
         Please read the instructions here: https://github.com/bioFAM/MOFA#installation
```

This points to the old MOFA implementation so I'm not sure if following the commands there is recommended. Any tips or advice about how to install them?

**Comment by gtca** [comment] 2020-05-12 11:55
Hey @llrs, please take a look if installing MOFA+ Python package (`mofapy2` instead of `mofapy`) could resolve this problem.
If needed, there's also `reticulate::use_python()` to choose the Python installation you want to use.

The CLL vignette you linked is from MOFA v1 package. For the new version you can find the vignette [here on GitHub](https://github.com/bioFAM/MOFA2/blob/master/MOFA2/vignettes/CLL.Rmd).

**Comment by llrs** [comment] 2020-05-12 12:40
Thanks for the quick reply.

I installed the new mofapy2:

```
Successfully built mofapy2
Installing collected packages: mofapy2
Successfully installed mofapy2-0.5.3
```

But got the same issue (if it is looking for `mofapy` I think it wouldn't find the `mofapy2` package).

At the moment I don't want to change the python version used. 

Not sure if it is related to the version of the vignette, as I got the same error following several versions of the vignette. The linked vignette is from the official vignette from Bioconductor of the current release. If these vignettes are not the officials, please update those on Bioconductor for future users. Besides, if I follow the [vignette](http://bioconductor.org/packages/3.11/bioc/vignettes/MOFA/inst/doc/MOFA_example_CLL.html) for the package I have installed I still find the same error.

**Comment by rargelaguet** [comment] 2020-05-12 14:22
Hi Lluis,
I think there is a confusion on the versions. MOFA v1 is on Bioconductor and this is the vignette that you are following. MOFA2 (or MOFA+) is not yet in Bioconductor and has to be installed from this github repository. What @gtca posted is the updated CLL vignette using MOFA2.

This comment should be posted on the MOFA v1 github (https://github.com/bioFAM/MOFA). But as @gtca mentioned, the problem is that R is not finding the python binary where mofapy is installed. This usually happens when you have multiple python binaries installed. It is fixed by setting the right python path using `reticulate::set_python(PATH, required=TRUE)`

https://github.com/bioFAM/MOFA

**Comment by llrs** [comment] 2020-05-12 15:44
Hi @rargelaguet, 

Yes, it is confusing. Just to make sure that I understood the situation I'll summarize here my confusion/thoughts. There are two repositories about MOFA here on github this repository and https://github.com/bioFAM/MOFA/, and then the Bioconductor one. 

The first one was marked as deprecated on Feb 18 (that's why I opened the issue here) and as far as I know that repository is synchronized with the one on Bioconductor, but the package was not deprecated from Bioconductor on the latest release (it stills show on https://bioconductor.org/packages/release/MOFA/) and should still work on the previous version of R or on the newest R version.

On Bioconductor the packages uses semantic versioning. And with the last release the one on the Bioconductor page is at version 1.4.0. But here use a different scheme, maybe because you change the name of the package to MOFA2. 

What are the advantages of MOFA2 over the package provided through Bioconductor? 
Should I use the MOFA functions as provided from Bioconductor following the vignette of this package?

-----

If I set the path to python but it is not available (both python3.5 and python 2.7) if I do it this way:

(I didn't found the `reticulate::set_python function` I used the one provided by the latest `reticulate` version that seems to do the same) 

```
> use_python("/usr/bin/python3.5", required = TRUE)
> py_install("mofapy", envname = "r-reticulate", method="auto")
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mofapy

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


Error: one or more Python packages failed to install [error code 1]

```

However, on another machine where this is all installed : 

```r
R6.3> library("reticulate")
R6.3> use_python("/usr/bin/python", required = TRUE)
R6.3> py_install("mofapy", envname = "r-reticulate", method="auto")
Using virtual environment 'r-reticulate' ...
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: mofapy in ./.virtualenvs/r-reticulate/lib/python2.7/site-packages (1.2)
Requirement already satisfied, skipping upgrade: h5py in /usr/local/lib/python2.7/dist-packages (from mofapy) (2.7.0)
Requirement already satisfied, skipping upgrade: scipy in /usr/local/lib/python2.7/dist-packages (from mofapy) (0.17.0)
Requirement already satisfied, skipping upgrade: argparse in /usr/lib/python2.7 (from mofapy) (1.2.1)
Requirement already satisfied, skipping upgrade: pandas in /usr/local/lib/python2.7/dist-packages (from mofapy) (0.18.0)
Requirement already satisfied, skipping upgrade: numpy in /usr/lib/python2.7/dist-packages (from mofapy) (1.8.2)
Requirement already satisfied, skipping upgrade: sklearn in ./.virtualenvs/r-reticulate/lib/python2.7/site-packages (from mofapy) (0.0)
Requirement already satisfied, skipping upgrade: six in /usr/lib/python2.7/dist-packages (from h5py->mofapy) (1.11.0)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/lib/python2.7/dist-packages (from pandas->mofapy) (1.5)
Requirement already satisfied, skipping upgrade: pytz>=2011k in /usr/lib/python2.7/dist-packages (from pandas->mofapy) (2012rc0)
Requirement already satisfied, skipping upgrade: scikit-learn in ./.virtualenvs/r-reticulate/lib/python2.7/site-packages (from sklearn->mofapy) (0.20.4)
```

It still fails:

<details>
```r
R6.3> ## ---- warning=FALSE, message=FALSE--------------------------------------------
R6.3> library(MultiAssayExperiment)
Loading required package: SummarizedExperiment
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Loading required package: S4Vectors

Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Loading required package: IRanges
Loading required package: GenomeInfoDb
Loading required package: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: DelayedArray
Loading required package: matrixStats

Attaching package: ‘matrixStats’

The following objects are masked from ‘package:Biobase’:

    anyMissing, rowMedians

Loading required package: BiocParallel

Attaching package: ‘DelayedArray’

The following objects are masked from ‘package:matrixStats’:

    colMaxs, colMins, colRanges, rowMaxs, rowMins, rowRanges

The following objects are masked from ‘package:base’:

    aperm, apply, rowsum

R6.3> library(MOFA)

Attaching package: ‘MOFA’

The following objects are masked from ‘package:Biobase’:

    featureNames, featureNames<-, sampleNames, sampleNames<-

The following object is masked from ‘package:stats’:

    predict

R6.3> library(MOFAdata)
R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> data("CLL_data")
R6.3> MOFAobject <- createMOFAobject(CLL_data)
Creating MOFA object from a list of matrices 
 please make sure that samples are stored in the columns and features in the rows...

R6.3> MOFAobject
Untrained MOFA model with the following characteristics: 
  Number of views: 4 
  View names: Drugs Methylation mRNA Mutations 
  Number of features per view: 310 4248 5000 69
  Number of samples: 200 
R6.3> 
R6.3> ## ---- warning=FALSE, message=FALSE--------------------------------------------
R6.3> 
R6.3> # Load data
R6.3> # import list with mRNA, Methylation, Drug Response and Mutation data. 
R6.3> data("CLL_data") 
R6.3> 
R6.3> # check dimensionalities, samples are columns, features are rows
R6.3> lapply(CLL_data, dim) 
$Drugs
[1] 310 200

$Methylation
[1] 4248  200

$mRNA
[1] 5000  200

$Mutations
[1]  69 200

R6.3> 
R6.3> # Load sample metadata: Sex and Diagnosis
R6.3> data("CLL_covariates")
R6.3> head(CLL_covariates)
     Gender Diagnosis
H045      m       CLL
H109      m       CLL
H024      m       CLL
H056      m       CLL
H079      m       CLL
H164      f       CLL
R6.3> 
R6.3> # Create MultiAssayExperiment object 
R6.3> mae_CLL <- MultiAssayExperiment(
+   experiments = CLL_data, 
+   colData = CLL_covariates
+ )
R6.3> 
R6.3> # Build the MOFA object
R6.3> MOFAobject <- createMOFAobject(mae_CLL)
Creating MOFA object from a MultiAssayExperiment object...
R6.3> MOFAobject
Untrained MOFA model with the following characteristics: 
  Number of views: 4 
  View names: Drugs Methylation mRNA Mutations 
  Number of features per view: 310 4248 5000 69
  Number of samples: 200 
R6.3> 
R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> plotDataOverview(MOFAobject)
R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> DataOptions <- getDefaultDataOptions()
R6.3> DataOptions 
$scaleViews
[1] FALSE

$removeIncompleteSamples
[1] FALSE

R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> ModelOptions <- getDefaultModelOptions(MOFAobject)
R6.3> ModelOptions$numFactors <- 25
R6.3> ModelOptions
$likelihood
      Drugs Methylation        mRNA   Mutations 
 "gaussian"  "gaussian"  "gaussian" "bernoulli" 

$numFactors
[1] 25

$sparsity
[1] TRUE

R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> TrainOptions <- getDefaultTrainOptions()
R6.3> 
R6.3> # Automatically drop factors that explain less than 2% of variance in all omics
R6.3> TrainOptions$DropFactorThreshold <- 0.02
R6.3> 
R6.3> TrainOptions$seed <- 2017
R6.3> 
R6.3> TrainOptions
$maxiter
[1] 5000

$tolerance
[1] 0.1

$DropFactorThreshold
[1] 0.02

$verbose
[1] FALSE

$seed
[1] 2017

R6.3> 
R6.3> ## -----------------------------------------------------------------------------
R6.3> MOFAobject <- prepareMOFA(
+   MOFAobject, 
+   DataOptions = DataOptions,
+   ModelOptions = ModelOptions,
+   TrainOptions = TrainOptions
+ )
Checking data options...
Checking training options...
Checking model options...
R6.3> MOFAobject <- runMOFA(MOFAobject)
[1] "No output file provided, using a temporary file..."
Error in value[[3L]](cond) : 
  mofapy package not found. Make sure that Reticulate is pointing to the right Python binary.
         Please read the instructions here: https://github.com/bioFAM/MOFA#installation
```
</details>

Many thanks for your assitance

**Comment by gtca** [comment] 2020-06-03 20:32
Just to get back to that discussion, there are a few comments.

There's indeed [MOFA v1 on GitHub](https://github.com/bioFAM/MOFA/ ), which is currently labelled as deprecated, and MOFA+ is the latest MOFA version we now suggest to use.

Bioconductor is just one of the ways to distribute and to version code. Surely, a version of software on GitHub is going to be different from what's available on GitHub, if code is released in multiple ways. Surely, MOFA v1 still works, and it is the version for last few Bioconductor releases.

So if you intend to use MOFA v1, and something doesn't work for you, please feel free to open an issue in a [relevant repository](https://github.com/bioFAM/MOFA/ ).

This is MOFA+ repository, and currently MOFA+ is only distributed via GitHub. Installing R packages from GitHub is as easy as with Bioconductor (`remotes::install_github("bioFAM/MOFA2/MOFA2"`) but please not that this way doesn't offer uniformity of software versions across packages as Bioconductor does with its releases.

I hope that clarifies a few things and reduces the confusion with different software versions.

For this MOFA+ repository, the software you would need to install is `mofapy2` rather than `mofapy`. But in case you want to use MOFA v1 — and to address the technical part of your question, —  it seems that `py_install` only searches for `mofapy` in a few channels that do not have `mofapy`. It is however available in the bioconda channel, please take a look at [details how to install it here](https://anaconda.org/bioconda/mofapy).

**Closed by gtca** 2020-06-03 20:32 UTC
